export const EVROPEYSKA_SOLIDARNIST = 'Європейська Солідарність'
export const SLUGA_NARODU = 'Слуга Народа'
export const BATKIVSCHYNA = 'Батьківщина'
export const OPZj = 'ОПЗЖ'
export const GOLOs = 'Голос'